---
- name: Install Gnome Terminal and xterm package
  hosts: all
  become: yes

  tasks:
    - name: Install Gnome Terminal
      yum:
        name: gnome-terminal.x86_64
        state: present
    - name: Install xterm package
      yum:
        name: xterm.x86_64
        state: present
